# Servidor y Microservicio
spring.application.name=ms-pedidos360-orders
server.port=8081

# Azure AD (Entra External ID)
spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=015cb7e6-81ea-4cf7-8d6c-b3538ca54b72
spring.cloud.azure.active-directory.credential.client-id=e87b8d53-b3ad-4c9a-a4d5-4f1c37c4735c
spring.cloud.azure.active-directory.app-id-uri=api://tallerpro360
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/015cb7e6-81ea-4cf7-8d6c-b3538ca54b72/v2.0

# Configuración de Conexión a NeonDB (PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-jolly-mouse-ac01fnqk-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_UCmZPNnVwu30
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración RabbitMQ (Tareas / Comandos Asíncronos)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.acknowledge-mode=manual

# Configuración Apache Kafka (Streaming / Auditoría y KPIs)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=orders-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer